# Display line breaks for readonly textarea fields
PublicHealthEngland/ndr_ui pull request #42
Opened 2021-09-23 22:42 UTC by suezhou

https://ncr.plan.io/issues/27972

2021-09-24 07:30 UTC, kenny-lee-1 commented on app/builders/ndr_ui/bootstrap/readonly.rb
> +        [:text_area].each do |selector|
`%i[text_area]` ?

2021-09-24 07:31 UTC, kenny-lee-1 commented on app/builders/ndr_ui/bootstrap/readonly.rb
> +              return super unless readonly?
blank line after return to keep rubocop happy

2022-05-17 10:26 UTC, kenny-lee-1 submitted a review, later dismissed

2024-05-17 10:12 UTC, ollietulloch approved these changes

2024-05-17 10:17 UTC, ollietulloch requested changes
Sorry, commentedon wrong PR!

2024-05-17 10:21 UTC, suezhou commented
@ollietulloch I think you replied to the wrong PR

PS Matrix is blocking the merging if we can't get the status. This PR is just too old.

2024-05-17 10:22 UTC, ollietulloch approved these changes

2024-05-17 10:23 UTC, ollietulloch commented
> @ollietulloch I think you replied to the wrong PR
> 
> PS Matrix is blocking the merging if we can't get the status. This PR is just too old.

Can we remove this PR and create another @suezhou?

2024-05-17 10:30 UTC, suezhou commented
code recommit in #52

2024-05-17 10:30 UTC, closed without merging